app = "nicolaus-daniel-2"
primary_region = "ams" # unaweza kubadilisha kama unataka region nyingine

[build]
dockerfile = "Dockerfile"

[env]
PORT = "3000"

[[services]]
internal_port = 3000
protocol = "tcp"

  [[services.ports]]
  handlers = ["http"]
  port = 80

  [[services.ports]]
  handlers = ["tls", "http"]
  port = 443
